/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2;

/**
 *
 * @author Admin
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hienthiketqua = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        canbac2 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        phantram = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        phanso = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        soduongvasoam = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        ketqua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hienthiketqua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hienthiketqua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hienthiketqua.setText("0");
        hienthiketqua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hienthiketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiketquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienthiketqua)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienthiketqua, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        so1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so1.setText("1");
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so1);

        so2.setFont(so2.getFont().deriveFont((float)24));
        so2.setText("2");
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so2ActionPerformed(evt);
            }
        });
        jPanel2.add(so2);

        so3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so3.setText("3");
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so3ActionPerformed(evt);
            }
        });
        jPanel2.add(so3);

        chia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        jPanel2.add(chia);

        canbac2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        canbac2.setText("sqrt");
        jPanel2.add(canbac2);

        so4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so4.setText("4");
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so4ActionPerformed(evt);
            }
        });
        jPanel2.add(so4);

        so5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so5.setText("5");
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so5ActionPerformed(evt);
            }
        });
        jPanel2.add(so5);

        so6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so6.setText("6");
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so6ActionPerformed(evt);
            }
        });
        jPanel2.add(so6);

        nhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nhan.setText("*");
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPanel2.add(nhan);

        phantram.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phantram.setText("%");
        phantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phantramActionPerformed(evt);
            }
        });
        jPanel2.add(phantram);

        so7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so7.setText("7");
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so7ActionPerformed(evt);
            }
        });
        jPanel2.add(so7);

        so8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so8.setText("8");
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so8ActionPerformed(evt);
            }
        });
        jPanel2.add(so8);

        so9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so9.setText("9");
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        jPanel2.add(so9);

        tru.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPanel2.add(tru);

        phanso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phanso.setText("1/x");
        jPanel2.add(phanso);

        so0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so0.setText("0");
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so0ActionPerformed(evt);
            }
        });
        jPanel2.add(so0);

        soduongvasoam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        soduongvasoam.setText("+/-");
        soduongvasoam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soduongvasoamActionPerformed(evt);
            }
        });
        jPanel2.add(soduongvasoam);

        xoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        xoa.setText("C");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel2.add(xoa);

        cong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(cong);

        ketqua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ketqua.setText("=");
        ketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketquaActionPerformed(evt);
            }
        });
        jPanel2.add(ketqua);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hienthiketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiketquaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hienthiketquaActionPerformed

    private void soduongvasoamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soduongvasoamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soduongvasoamActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoaActionPerformed

    private void phantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phantramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phantramActionPerformed

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so1.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so1ActionPerformed

    private void so2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so2ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so2.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so2ActionPerformed

    private void so3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so3ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so3.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so3ActionPerformed

    private void so4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so4ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so4.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so4ActionPerformed

    private void so5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so5ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so5.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so5ActionPerformed

    private void so6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so6ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so6.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so6ActionPerformed

    private void so7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so7ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so7.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so7ActionPerformed

    private void so8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so8ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so8.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so8ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so9.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so9ActionPerformed

    private void so0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so0ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthiketqua.getText();
        if (gt.length()<12)
            if (gt.equals("0")) gt="";
        long so= Long.parseLong(gt+ so0.getText());
        this.hienthiketqua.setText(String.valueOf(so));
    }//GEN-LAST:event_so0ActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthiketqua.getText());
        if (this.a !=0){
            this.pheptoan="/";
            this.hienthiketqua.setText("0");
        }
    }//GEN-LAST:event_chiaActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
        // TODO add your handling code here:
      this.a = Long.parseLong(this.hienthiketqua.getText());
      this.pheptoan = "*";
      this.hienthiketqua.setText("0");

    }//GEN-LAST:event_nhanActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        // TODO add your handling code here:
      this.a = Long.parseLong(this.hienthiketqua.getText());
      this.pheptoan = "-";
      this.hienthiketqua.setText("0");
    }//GEN-LAST:event_truActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthiketqua.getText());
      this.pheptoan = "+";
      this.hienthiketqua.setText("0");
    }//GEN-LAST:event_congActionPerformed

    private void ketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketquaActionPerformed
        // TODO add your handling code here:
        if (this.pheptoan.length()>0){
            long b=Long.parseLong(this.hienthiketqua.getText());
            if (this.pheptoan.equals("+")){
                long kq=this.a+b;
                this.hienthiketqua.setText(String.valueOf(kq));
            }
            else if (this.pheptoan.equals("-")){
                long kq=this.a-b;
                this.hienthiketqua.setText(String.valueOf(kq));
            }
            else if (this.pheptoan.equals("*")){
                long kq=this.a*b;
                this.hienthiketqua.setText(String.valueOf(kq));
            }
            else if (this.pheptoan.equals("/")){
                long kq=this.a/b;
                this.hienthiketqua.setText(String.valueOf(kq));
            }
            this.pheptoan = "";
            this.a=0;
        }
    }//GEN-LAST:event_ketquaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Calculator().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canbac2;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JTextField hienthiketqua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ketqua;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phanso;
    private javax.swing.JButton phantram;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton soduongvasoam;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
       private long a=0;
        private String pheptoan="";
}

